services:
  - type: web
    name: language-community-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/data/language-community.db
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 